name: pcdp
channels:
  - conda-forge
  - nvidia/label/cuda-12.1.0
  - nvidia
  - anaconda
  - pytorch
  - pytorch3d
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - _x86_64-microarch-level=4
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.12.15
  - aiosignal=1.4.0
  - alsa-lib=1.2.14
  - ampl-asl=1.0.0
  - annotated-types=0.7.0
  - antlr-python-runtime=4.9.3
  - aom=3.9.1
  - appdirs=1.4.4
  - asciitree=0.3.3
  - assimp=5.4.3
  - asttokens=3.0.0
  - async-timeout=5.0.1
  - attr=2.5.1
  - attrs=25.3.0
  - av=15.0.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.5
  - aws-c-http=0.10.4
  - aws-c-io=0.21.2
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.8.6
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.33.1
  - aws-sdk-cpp=1.11.606
  - azure-core-cpp=1.16.0
  - azure-identity-cpp=1.12.0
  - azure-storage-blobs-cpp=12.14.0
  - azure-storage-common-cpp=12.10.0
  - azure-storage-files-datalake-cpp=12.12.0
  - blas=2.108
  - blas-devel=3.9.0
  - blinker=1.9.0
  - blosc=1.21.6
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.34.5
  - c-blosc2=2.19.1
  - ca-certificates=2025.8.3
  - cairo=1.18.4
  - casadi=3.7.0
  - cccl=2.8.2
  - certifi=2025.8.3
  - cffi=1.17.1
  - charls=2.4.2
  - charset-normalizer=3.4.2
  - cli11=2.5.0
  - click=8.2.2
  - cloudpickle=3.1.1
  - cmake=4.0.3
  - coal=3.0.1
  - coal-python=3.0.1
  - colorama=0.4.6
  - comm=0.2.3
  - console_bridge=1.0.2
  - contourpy=1.3.2
  - cpython=3.10.18
  - cuda-cccl=12.9.27
  - cuda-cccl_linux-64=12.9.27
  - cuda-command-line-tools=12.1.0
  - cuda-compiler=12.1.0
  - cuda-crt-tools=12.9.86
  - cuda-cudart=12.1.105
  - cuda-cudart-dev=12.1.55
  - cuda-cudart-static=12.9.79
  - cuda-cudart-static_linux-64=12.9.79
  - cuda-cudart_linux-64=12.9.79
  - cuda-cuobjdump=12.9.82
  - cuda-cupti=12.1.105
  - cuda-cuxxfilt=12.9.82
  - cuda-documentation=12.1.55
  - cuda-driver-dev=12.9.79
  - cuda-driver-dev_linux-64=12.9.79
  - cuda-gdb=12.9.79
  - cuda-libraries=12.1.0
  - cuda-libraries-dev=12.1.0
  - cuda-libraries-static=12.9.1
  - cuda-nsight=12.9.79
  - cuda-nsight-compute=12.1.0
  - cuda-nvcc=12.1.66
  - cuda-nvcc-tools=12.9.86
  - cuda-nvdisasm=12.9.88
  - cuda-nvml-dev=12.9.79
  - cuda-nvprof=12.9.79
  - cuda-nvprune=12.9.82
  - cuda-nvrtc=12.1.105
  - cuda-nvrtc-dev=12.1.55
  - cuda-nvrtc-static=12.9.86
  - cuda-nvtx=12.1.105
  - cuda-nvvm-tools=12.9.86
  - cuda-nvvp=12.9.79
  - cuda-opencl=12.9.19
  - cuda-opencl-dev=12.1.56
  - cuda-profiler-api=12.9.79
  - cuda-runtime=12.1.0
  - cuda-sanitizer-api=12.9.79
  - cuda-toolkit=12.1.0
  - cuda-tools=12.1.0
  - cuda-version=12.9
  - cuda-visual-tools=12.1.0
  - cudnn=9.11.0.98
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dash=3.1.1
  - dataclasses=0.8
  - datasets=3.6.0
  - dav1d=1.2.1
  - dbus=1.16.2
  - debugpy=1.8.17
  - decorator=5.2.1
  - diffusers=0.34.0
  - dill=0.3.8
  - docker-pycreds=0.4.0
  - double-conversion=3.3.1
  - easydict=1.13
  - eigen=3.4.0
  - eigenpy=3.11.0
  - einops=0.7.0
  - elfutils=0.193
  - embree=4.4.0
  - eval_type_backport=0.2.2
  - evdev=1.9.2
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - fasteners=0.19
  - ffmpeg=7.1.1
  - filelock=3.18.0
  - flask=3.1.1
  - fmt=11.2.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.59.0
  - freeglut=3.2.2
  - freetype=2.13.3
  - fribidi=1.0.10
  - frozenlist=1.7.0
  - fsspec=2025.3.0
  - fvcore=0.1.5.post20221221
  - gdbm=1.18
  - gdk-pixbuf=2.42.12
  - gds-tools=1.14.1.1
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - gflags=2.2.2
  - giflib=5.2.2
  - gitdb=4.0.12
  - gitpython=3.1.45
  - gl2ps=1.4.2
  - glew=2.1.0
  - glfw=3.4
  - glib=2.84.3
  - glib-tools=2.84.3
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.8.9
  - graphite2=1.3.14
  - gst-plugins-base=1.24.11
  - gstreamer=1.24.11
  - gym=0.26.1
  - gym-notices=0.1.0
  - h2=4.2.0
  - harfbuzz=11.3.3
  - hdf4=4.2.15
  - hdf5=1.14.6
  - hf-xet=1.1.6
  - hpack=4.1.0
  - hpp-fcl=3.0.1
  - huggingface_hub=0.34.3
  - hydra-core=1.3.2
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - imagecodecs=2025.3.30
  - imageio=2.37.0
  - imath=3.1.12
  - importlib-metadata=8.7.0
  - iopath=0.1.10
  - ipopt=3.14.17
  - ipykernel=6.30.1
  - ipython=8.37.0
  - itsdangerous=2.2.0
  - jasper=4.2.7
  - jedi=0.19.2
  - jinja2=3.1.6
  - jsoncpp=1.9.6
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jxrlib=1.1
  - keyutils=1.6.1
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lame=3.100
  - lazy-loader=0.4
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - level-zero=1.24.1
  - libabseil=20250512.1
  - libaec=1.1.4
  - libarchive=3.8.1
  - libarrow=21.0.0
  - libarrow-acero=21.0.0
  - libarrow-compute=21.0.0
  - libarrow-dataset=21.0.0
  - libarrow-substrait=21.0.0
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libass=0.17.4
  - libavif16=1.3.0
  - libblas=3.9.0
  - libblasfeo=0.1.4.2
  - libboost=1.88.0
  - libboost-devel=1.88.0
  - libboost-headers=1.88.0
  - libboost-python=1.88.0
  - libboost-python-devel=1.88.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.75
  - libcblas=3.9.0
  - libclang-cpp20.1=20.1.8
  - libclang13=20.1.8
  - libcoal=3.0.1
  - libcrc32c=1.1.2
  - libcublas=12.1.0.26
  - libcublas-dev=12.1.0.26
  - libcublas-static=12.9.1.4
  - libcudnn=9.11.0.98
  - libcudnn-dev=9.11.0.98
  - libcudss=0.6.0.5
  - libcufft=11.0.2.4
  - libcufft-dev=11.0.2.4
  - libcufft-static=11.4.1.4
  - libcufile=1.14.1.1
  - libcufile-dev=1.14.1.1
  - libcufile-static=1.14.1.1
  - libcups=2.3.3
  - libcurand=10.3.10.19
  - libcurand-dev=10.3.10.19
  - libcurand-static=10.3.10.19
  - libcurl=8.14.1
  - libcusolver=11.4.4.55
  - libcusolver-dev=11.4.4.55
  - libcusolver-static=11.7.5.82
  - libcusparse=12.0.2.55
  - libcusparse-dev=12.0.2.55
  - libcusparse-static=12.5.10.65
  - libdeflate=1.24
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.1
  - libfatrop=0.0.4
  - libffi=3.4.6
  - libflac=1.4.3
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgcrypt-lib=1.11.1
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgfortran=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libgl=1.7.0
  - libglib=2.84.3
  - libglu=9.0.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.1.0
  - libgoogle-cloud=2.39.0
  - libgoogle-cloud-storage=2.39.0
  - libgpg-error=1.55
  - libgrpc=1.73.1
  - libgz-cmake3=3.5.3
  - libgz-cmake4=4.2.0
  - libgz-math7=7.5.2
  - libgz-tools2=2.0.1
  - libgz-utils2=2.2.0
  - libhwloc=2.11.2
  - libhwy=1.2.0
  - libiconv=1.18
  - libidn2=2.3.8
  - libjpeg-turbo=3.1.0
  - libjxl=0.11.1
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm20=20.1.8
  - liblzf=3.6
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libmagma=2.8.0
  - libmicrohttpd=1.0.2
  - libnetcdf=4.9.2
  - libnghttp2=1.64.0
  - libnl=3.11.0
  - libnpp=12.0.2.50
  - libnpp-dev=12.0.2.50
  - libnpp-static=12.4.1.87
  - libnsl=2.0.1
  - libntlm=1.8
  - libnuma=2.0.18
  - libnvfatbin-static=12.9.82
  - libnvjitlink=12.1.105
  - libnvjitlink-dev=12.1.55
  - libnvjitlink-static=12.9.86
  - libnvjpeg=12.1.1.14
  - libnvjpeg-dev=12.1.0.39
  - libnvjpeg-static=12.4.0.76
  - libnvvm-samples=12.1.55
  - libogg=1.3.5
  - libopenblas=0.3.29
  - libopencv=4.12.0
  - libopengl=1.7.0
  - libopentelemetry-cpp=1.21.0
  - libopentelemetry-cpp-headers=1.21.0
  - libopenvino=2025.2.0
  - libopenvino-auto-batch-plugin=2025.2.0
  - libopenvino-auto-plugin=2025.2.0
  - libopenvino-hetero-plugin=2025.2.0
  - libopenvino-intel-cpu-plugin=2025.2.0
  - libopenvino-intel-gpu-plugin=2025.2.0
  - libopenvino-intel-npu-plugin=2025.2.0
  - libopenvino-ir-frontend=2025.2.0
  - libopenvino-onnx-frontend=2025.2.0
  - libopenvino-paddle-frontend=2025.2.0
  - libopenvino-pytorch-frontend=2025.2.0
  - libopenvino-tensorflow-frontend=2025.2.0
  - libopenvino-tensorflow-lite-frontend=2025.2.0
  - libopus=1.5.2
  - libosqp=1.0.0
  - libparquet=21.0.0
  - libpciaccess=0.18
  - libpng=1.6.50
  - libpq=17.5
  - libprotobuf=6.31.1
  - libqdldl=0.1.8
  - libre2-11=2025.07.22
  - librsvg=2.58.4
  - libscotch=7.0.4
  - libsdformat14=14.8.0
  - libsndfile=1.2.2
  - libsodium=1.0.20
  - libspral=2025.03.06
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libsystemd0=257.7
  - libtasn1=4.20.0
  - libtheora=1.1.1
  - libthrift=0.22.0
  - libtiff=4.7.0
  - libudev1=257.7
  - libunistring=0.9.10
  - libunwind=1.8.2
  - liburing=2.11
  - libusb=1.0.29
  - libutf8proc=2.10.0
  - libuuid=2.38.1
  - libuv=1.51.0
  - libva=2.22.0
  - libvorbis=1.3.7
  - libvpx=1.14.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.10.0
  - libxkbfile=1.1.0
  - libxml2=2.13.8
  - libxslt=1.1.43
  - libzip=1.11.2
  - libzlib=1.3.1
  - libzopfli=1.0.3
  - llvm-openmp=15.0.7
  - llvmlite=0.44.0
  - loguru=0.7.3
  - lz4-c=1.10.0
  - lzo=2.10
  - markupsafe=3.0.2
  - matplotlib=3.7.0
  - matplotlib-base=3.7.0
  - matplotlib-inline=0.1.7
  - metis=5.1.0
  - mkl=2020.4
  - mkl-devel=2020.4
  - mkl-include=2020.4
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.32.9
  - mpmath=1.3.0
  - msgpack-python=1.1.1
  - multidict=6.6.3
  - multiprocess=0.70.16
  - mumps-include=5.7.3
  - mumps-seq=5.7.3
  - munkres=1.1.4
  - narwhals=2.0.1
  - nccl=2.27.7.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nettle=3.10.1
  - networkx=3.4.2
  - nlohmann_json=3.12.0
  - nomkl=2.0
  - nsight-compute=2025.2.1.3
  - nspr=4.37
  - nss=3.114
  - numba=0.61.2
  - numcodecs=0.13.1
  - numpy=1.26.4
  - ocl-icd=2.3.3
  - octomap=1.10.0
  - omegaconf=2.3.0
  - open3d=0.19.0
  - openblas-devel=0.3.29
  - opencl-headers=2025.06.13
  - openexr=3.3.5
  - openh264=2.6.0
  - openjpeg=2.5.3
  - openldap=2.6.10
  - openssl=3.5.3
  - optree=0.17.0
  - orc=2.2.0
  - p11-kit=0.24.1
  - packaging=25.0
  - pandas=2.3.1
  - pango=1.56.4
  - parso=0.8.5
  - pcre2=10.45
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pinocchio=3.7.0
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.3.8
  - plotly=6.2.0
  - ply=3.11
  - portalocker=3.2.0
  - proj=9.6.2
  - prometheus-cpp=1.3.0
  - prompt-toolkit=3.0.52
  - propcache=0.3.1
  - protobuf=6.31.1
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pugixml=1.15
  - pulseaudio-client=17.0
  - pure_eval=0.2.3
  - py-opencv=4.12.0
  - pyarrow=21.0.0
  - pyarrow-core=21.0.0
  - pybind11=3.0.0
  - pybind11-global=3.0.0
  - pycparser=2.22
  - pydantic=2.11.7
  - pydantic-core=2.33.2
  - pygments=2.19.2
  - pynput=1.8.1
  - pyparsing=3.2.3
  - pyqt=5.15.11
  - pyqt5-sip=12.17.0
  - pyserial=3.5
  - pyside6=6.9.1
  - pysocks=1.7.1
  - python=3.10.18
  - python-can=4.5.0
  - python-dateutil=2.9.0.post0
  - python-gil=3.10.18
  - python-tzdata=2025.2
  - python-xlib=0.33
  - python-xxhash=3.5.0
  - python_abi=3.10
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pytorch3d=0.7.8
  - pytz=2025.2
  - pywavelets=1.8.0
  - pyyaml=6.0.2
  - pyzmq=27.1.0
  - qhull=2020.2
  - qhull-static=2020.2
  - qt-main=5.15.15
  - qt6-main=6.9.1
  - rav1e=0.7.1
  - rdma-core=58.0
  - re2=2025.07.22
  - readline=8.2
  - regex=2025.7.34
  - requests=2.32.4
  - retrying=1.4.2
  - rhash=1.4.6
  - ruby=3.4.5
  - s2n=1.5.23
  - safetensors=0.5.3
  - scikit-image=0.25.2
  - scikit-video=1.1.11
  - scipy=1.15.2
  - sdl2=2.32.54
  - sdl3=3.2.20
  - sentry-sdk=2.34.1
  - setproctitle=1.3.6
  - setuptools=80.9.0
  - sip=6.10.0
  - six=1.17.0
  - sleef=3.8
  - smmap=5.0.2
  - snappy=1.2.2
  - sqlite=3.50.4
  - stack_data=0.6.3
  - svt-av1=3.0.2
  - tabulate=0.9.0
  - tbb=2022.1.0
  - termcolor=2.0.1
  - threadpoolctl=3.6.0
  - tifffile=2025.5.10
  - tinyobjloader=1.0.7
  - tinyxml2=11.0.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.2.1
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing=3.10.0.0
  - typing-extensions=4.14.1
  - typing-inspection=0.4.1
  - typing_extensions=4.14.1
  - tzdata=2025b
  - unicodedata2=16.0.0
  - urdfdom=4.0.1
  - urdfdom_headers=1.1.2
  - urllib3=2.5.0
  - utfcpp=4.0.6
  - vtk-base=9.4.2
  - wandb=0.21.0
  - wayland=1.24.0
  - wayland-protocols=1.45
  - wcwidth=0.2.14
  - werkzeug=3.1.3
  - wheel=0.45.1
  - wrapt=1.17.2
  - wslink=2.3.4
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.45
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxinerama=1.1.5
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxscrnsaver=1.2.4
  - xorg-libxshmfence=1.3.3
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - xxhash=0.8.3
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yacs=0.1.8
  - yaml=0.2.5
  - yarl=1.20.1
  - zarr=2.18.3
  - zeromq=4.3.5
  - zfp=1.0.1
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.2.4
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - atomics==1.0.3
      - minkowskiengine==0.5.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - pcdp==0.0.0
      - piper-sdk==0.4.1
      - pybind11-stubgen==2.5.4
      - pyrealsense2==2.56.5.9235
      - sam-2==1.0
      - sympy==1.13.1
      - torch==2.5.1+cu121
      - torchaudio==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - triton==3.1.0
