defaults:
  - task: RISE_stack

name: train_diffusion_RISE
_target_: pcdp.workspace.train_diffusion_RISE_workspace.TrainRISEWorkspace

task_name: ${task.name}
exp_name: "debug"

policy:
  _target_: pcdp.policy.diffusion_RISE_policy.RISEPolicy
  num_action: 20
  input_dim: 6
  obs_feature_dim: 512
  hidden_dim: 512
  nheads: 8
  num_encoder_layers: 4
  num_decoder_layers: 1
  dropout: 0.1

ema:
  _target_: pcdp.model.diffusion.ema_model.EMAModel
  update_after_step: 0
  inv_gamma: 1.0
  power: 0.75
  min_value: 0.0
  max_value: 0.9999

dataloader:
  batch_size: 150
  num_workers: 15
  shuffle: True
  drop_last: True

val_dataloader:
  batch_size: 150
  num_workers: 15
  shuffle: False
  drop_last: False

optimizer:
  _target_: torch.optim.AdamW
  lr: 3.0e-4
  betas: [0.95, 0.999]
  eps: 1.0e-8
  weight_decay: 1.0e-6

training:
  device: "cuda:0"
  seed: 233
  debug: True
  resume: True
  lr_warmup_steps: 2000
  num_epochs: 1000
  use_ema: False
  rollout_every: 5
  save_epochs: 5
  tqdm_interval_sec: 1.0
  validation_every: 5

logging:
  group: ${exp_name}
  id: null
  mode: online
  name: "moai_${now:%Y.%m.%d}"
  project: rise
  resume: true
  tags:
  - rise

checkpoint:
  save_ckpt: True
  save_last_ckpt: True
  save_last_snapshot: False

multi_run:
  run_dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  wandb_name_base: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  sweep:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
    subdir: ${hydra.job.num}